#pragma once

#define DEFAULT_WIDTH 1280
#define DEFAULT_HEIGHT 720
#define DEFAULT_TITLE "OpenGL Game Engine by András Kmeczó, 2019"
#define DEFAULT_FULLSCREEN false

#define FS_WINDOW_WIDTH 1920
#define FS_WINDOW_HEIGHT 1080

#define NM_WINDOW_WIDTH 1280
#define NM_WINDOW_HEIGHT 720

#define WINDOW_FULLSCREEN false

#define WINDOW_WIDTH WINDOW_FULLSCREEN ? FS_WINDOW_WIDTH : NM_WINDOW_WIDTH
#define WINDOW_HEIGHT WINDOW_FULLSCREEN ? FS_WINDOW_HEIGHT : NM_WINDOW_HEIGHT
#define WINDOW_TITLE "Game"